language: ruby
rvm:
- 1.9.3
deploy:
  provider: rubygems
  api_key:
    secure: GTH+rO2iodGGkNBth4yGyJ3XUxibVCE9MLqC+kB1aL+H35QGXZjGw8QFNCW2AMoYhsnjn6e1noP+hd6sm0qkU0a2JouArzqvr2+XLxmL2z1B/gt+WpUQJyYzYS94CJx6nQGpaJZKj+vLTN3pL/M3qLUvM8WsmqAcziO5BJBobzc=
  gem: vagrant-nuke
  on:
    tags: true
    repo: n00bworks/vagrant-nuke
